substitutions:
  _SERVICE_NAME: api-gateway

steps:
  # Step 1: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:f8b08c609fdc392ee6827ff3e1725e4980f7d96bde9f76f4695086405c96c147
    args:
      - build
      - --build-arg=HOSTNAME=$_DOMAIN
      - --build-arg=SERVICE_SUFFIX=$_SERVICE_SUFFIX
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - ./api-gateway

  # Step 2: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:f8b08c609fdc392ee6827ff3e1725e4980f7d96bde9f76f4695086405c96c147
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:c2f782e6cafeb04e8780921abdbb83ae948c7e03005671cd0c8bce3296718e60
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-east1
      - --allow-unauthenticated
      - --max-instances=10
      - --port=8080
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
