substitutions:
  _SERVICE_NAME: api-gateway

steps:
  # Step 1: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:29ff6d7f5e1dd1b3d5f33bc3d1fc3204e1eacf7a5ba622d63544fad111b3cadf
    args:
      - build
      - --build-arg=HOSTNAME=$_DOMAIN
      - --build-arg=SERVICE_SUFFIX=$_SERVICE_SUFFIX
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
      - .

  # Step 2: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:29ff6d7f5e1dd1b3d5f33bc3d1fc3204e1eacf7a5ba622d63544fad111b3cadf
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:323dd9faf4c7b98ab4ecd0acc2d82150cbd10069c243a8c7c79a909061b1248e
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-east1
      - --allow-unauthenticated
      - --max-instances=10
      - --port=8080
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
