substitutions:
  _SERVICE_NAME: api-gateway

steps:
  # Step 1: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:a209d5caa0fd953f0133d1fc1be0e7940fc29052d35da53786b29911575e3c40
    args:
      - build
      - --build-arg=HOSTNAME=$_DOMAIN
      - --build-arg=SERVICE_SUFFIX=$_SERVICE_SUFFIX
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - ./api-gateway

  # Step 2: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:a209d5caa0fd953f0133d1fc1be0e7940fc29052d35da53786b29911575e3c40
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:3115a006674d7d43905b66d543d99b65df1adf9590d20bcf8f1a2b059792d4a5
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-east1
      - --allow-unauthenticated
      - --max-instances=10
      - --port=8080
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
