substitutions:
  _SERVICE_NAME: api-gateway

steps:
  # Step 1: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:7b03de12c4f73120942e422ffe043f2b1baa97c560dac70b0b741cc9a031414f
    args:
      - build
      - --build-arg=HOSTNAME=$_DOMAIN
      - --build-arg=SERVICE_SUFFIX=$_SERVICE_SUFFIX
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - ./api-gateway

  # Step 2: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:7b03de12c4f73120942e422ffe043f2b1baa97c560dac70b0b741cc9a031414f
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:41d36cf4e435888282c99f0c92e50f7d3ee774135b26bc9b9ee7d5377e21b3f3
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-east1
      - --allow-unauthenticated
      - --max-instances=10
      - --port=8080
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
