substitutions:
  _SERVICE_NAME: api-gateway

steps:
  # Step 1: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:bc70c80c6e63f67661d764f4776c5c1a4f5a1a047304bb7eb3e94bcdf98f32da
    args:
      - build
      - --build-arg=HOSTNAME=$_DOMAIN
      - --build-arg=SERVICE_SUFFIX=$_SERVICE_SUFFIX
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - ./api-gateway

  # Step 2: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:bc70c80c6e63f67661d764f4776c5c1a4f5a1a047304bb7eb3e94bcdf98f32da
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:fa4e7d418452a14ebbf2d5c4ed1827d63625914f3bb3e918cd95a504ac317c7b
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-east1
      - --allow-unauthenticated
      - --max-instances=10
      - --port=8080
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
