FROM alpine:3.20.1@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0 as builder
WORKDIR /app
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN apk add --no-cache gettext=0.22.3-r0

ENV PORT 8080
ARG HOSTNAME
ENV HOSTNAME ${HOSTNAME}
ARG SERVICE_SUFFIX
ENV SERVICE_SUFFIX ${SERVICE_SUFFIX}

COPY envoy.template.yaml envoy.template.yaml
RUN envsubst < envoy.template.yaml > envoy.yaml

FROM envoyproxy/envoy:distroless-v1.28-latest@sha256:7dec57a59d913b6a769b0ff51e437b52eef8f268763d2f889d57ab2482a64f9b
COPY --from=builder /app/envoy.yaml /etc/envoy/envoy.yaml