version: "3.9"
services:
  server:
    build:
      context: .
      args:
        - SERVICE_SUFFIX=${SERVICE_SUFFIX}
        - HOSTNAME=${HOSTNAME}
    ports:
      - 8080:8080
      - 9901:9901
    env_file:
      - .env
