FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 as builder
WORKDIR /app
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN apk add --no-cache gettext=0.22.3-r0

ENV PORT 8080
ARG HOSTNAME
ENV HOSTNAME ${HOSTNAME}
ARG SERVICE_SUFFIX
ENV SERVICE_SUFFIX ${SERVICE_SUFFIX}

COPY envoy.template.yaml envoy.template.yaml
RUN envsubst < envoy.template.yaml > envoy.yaml

FROM envoyproxy/envoy:distroless-v1.28-latest@sha256:d3990f1a25ea8cb77a99f8bff7bf13ce2772416121cd52a979ea4b37798a866b
COPY --from=builder /app/envoy.yaml /etc/envoy/envoy.yaml