name: Auto Merge Bots

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  comment_pr_if_bot:
    name: Comment on pull request if bot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.pull_request.user.type == 'Bot' && !contains(github.event.pull_request.user.login, 'sweep.dev[bot]') }}
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ github.token }}
          sync-labels: true

      - uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308 # v2
        with:
          message: |
            /trunk merge
