name: Merge

permissions: read-all

on:
  push:
    branches:
      - trunk-merge/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Cache Bazel
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE','MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazelisk build //...
