name: Merge

permissions: read-all

on:
  push:
    branches:
      - trunk-merge/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Cache Bazel
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE','MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazelisk build //...
